// Logo mapping for all integrations
export const getServiceLogo = (integrationId: string): string => {
  const logoMap: Record<string, string> = {
    // AWS Services
    'aws-app-runner': '/logos/aws.svg',
    'aws-backup': '/logos/aws.svg',
    'aws-athena': '/logos/aws.svg',
    'aws-step-function': '/logos/aws.svg',
    'aws-ec2': '/logos/aws.svg',
    'aws-ecs': '/logos/aws.svg',
    'aws-appflow': '/logos/aws.svg',
    'aws-sns': '/logos/aws.svg',
    'aws-sqs': '/logos/aws.svg',
    'aws-sagemaker': '/logos/aws.svg',
    'aws-glue': '/logos/aws.svg',
    'aws-glue-databrew': '/logos/aws.svg',
    'aws-lambda': '/logos/aws.svg',
    'aws-emr': '/logos/aws.svg',
    'aws-redshift': '/logos/aws.svg',
    'aws-dynamodb': '/logos/aws.svg',
    'aws-datasync': '/logos/aws.svg',
    'aws-batch': '/logos/aws.svg',
    'aws-cloudformation': '/logos/aws.svg',
    'aws-data-pipeline': '/logos/aws.svg',
    'aws-m2': '/logos/aws.svg',
    'aws-mwaa': '/logos/aws.svg',
    'aws-quicksight': '/logos/aws.svg',
    'aws-database-migration-service': '/logos/aws.svg',
    
    // Azure Services
    'azure-data-factory': '/logos/azure.svg',
    'azure-backup': '/logos/azure.svg',
    'azure-batch': '/logos/azure.svg',
    'azure-container-instances': '/logos/azure.svg',
    'azure-devops': '/logos/azure.svg',
    'azure-functions': '/logos/azure.svg',
    'azure-hdinsight': '/logos/azure.svg',
    'azure-logic-apps': '/logos/azure.svg',
    'azure-machine-learning': '/logos/azure.svg',
    'azure-resource-management': '/logos/azure.svg',
    'azure-service-bus': '/logos/azure.svg',
    'azure-synapse': '/logos/azure.svg',
    'azure-vm': '/logos/azure.svg',
    'azure-databricks': '/logos/azure.svg',
    
    // GCP Services
    'gcp-vm': '/logos/gcp.svg',
    'gcp-functions': '/logos/gcp.svg',
    'gcp-cloud-run': '/logos/gcp.svg',
    'gcp-workflows': '/logos/gcp.svg',
    'gcp-composer': '/logos/gcp.svg',
    'gcp-batch': '/logos/gcp.svg',
    'gcp-bigquery': '/logos/gcp.svg',
    'gcp-dataflow': '/logos/gcp.svg',
    'gcp-dataplex': '/logos/gcp.svg',
    'gcp-dataprep': '/logos/gcp.svg',
    'gcp-dataproc': '/logos/gcp.svg',
    'gcp-data-fusion': '/logos/gcp.svg',
    'gcp-deployment-manager': '/logos/gcp.svg',
    
    // Oracle Cloud
    'oracle-cloud-vm': '/logos/oracle.svg',
    'oracle-cloud-data-integration': '/logos/oracle.svg',
    'oracle-cloud-data-flow': '/logos/oracle.svg',
    'oracle-cloud-data-science': '/logos/oracle.svg',
    'oci-functions': '/logos/oracle.svg',
    
    // Other Services
    'jenkins': '/logos/jenkins.svg',
    'docker': '/logos/docker.svg',
    'kubernetes': '/logos/kubernetes.svg',
    'terraform': '/logos/terraform.svg',
    'ansible-awx': '/logos/ansible.svg',
    'rabbitmq': '/logos/rabbitmq.svg',
    'snowflake': '/logos/snowflake.svg',
    'snowflake-idp': '/logos/snowflake.svg',
    'tableau': '/logos/tableau.svg',
    'microsoft-power-bi': '/logos/powerbi.svg',
    'microsoft-power-bi-sp': '/logos/powerbi.svg',
    'qlik-cloud': '/logos/qlik.svg',
    'airflow': '/logos/airflow.svg',
    'astronomer': '/logos/astronomer.svg',
    'fivetran': '/logos/fivetran.svg',
    'airbyte': '/logos/airbyte.svg',
    'dbt': '/logos/dbt.svg',
    'informatica-cs': '/logos/informatica.svg',
    'talend-data-management': '/logos/talend.svg',
    'talend': '/logos/talend.svg',
    'uipath': '/logos/uipath.svg',
    'automation-anywhere': '/logos/automation-anywhere.svg',
    'datadog': '/logos/datadog.svg',
    'pagerduty': '/logos/pagerduty.svg',
    'veritas-netbackup': '/logos/veritas.svg',
    'rubrik': '/logos/rubrik.svg',
    'veeam-backup': '/logos/veeam.svg',
    'vmware': '/logos/vmware.svg',
    'sap-btp-scheduler': '/logos/sap.svg',
    'micro-focus-windows': '/logos/microfocus.svg',
    'micro-focus-linux': '/logos/microfocus.svg',
    'web-services-rest': '/logos/swagger.svg',
    'web-services-soap': '/logos/swagger.svg',
    'communication-suite': '/logos/message.svg',
    'matillion': '/logos/matillion.svg',
    'alteryx-trifacta': '/logos/trifacta.svg',
    'apache-nifi': '/logos/nifi.svg',
    'boomi-atomsphere': '/logos/boomi.svg',
    'circleci': '/logos/circleci.svg',
    'ibm-datastage-linux': '/logos/generic.svg',
    'ibm-datastage-windows': '/logos/generic.svg',
  };
  
  return logoMap[integrationId] || '/logos/generic.svg';
};